// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjVsU6FU3b5nlMLA282bh5Du3XSx2EFWg',
    appId: '1:689813065514:android:6b5dac959440d573515853',
    messagingSenderId: '689813065514',
    projectId: 'ditonton-149aa',
    storageBucket: 'ditonton-149aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpSoSoQnD-2F9DODJGqYIp4Kf6a5y2W3U',
    appId: '1:689813065514:ios:1bf136bef4738a43515853',
    messagingSenderId: '689813065514',
    projectId: 'ditonton-149aa',
    storageBucket: 'ditonton-149aa.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLs3w_-GeDBim1ew-i7SiRhGZQOGn8eg',
    appId: '1:689813065514:web:51afe1046bd19c95515853',
    messagingSenderId: '689813065514',
    projectId: 'ditonton-149aa',
    authDomain: 'ditonton-149aa.firebaseapp.com',
    storageBucket: 'ditonton-149aa.appspot.com',
    measurementId: 'G-WBZZGNCSL0',
  );

}